name=BN_DHT11
version=1.0.0
author=BN STEM (Your Name)
maintainer=BN STEM
sentence=Thu vien doc cam bien nhiet do do am BN_DHT11 danh cho he sinh thai STEM BN.
paragraph=Thu vien toi uu code hoan toan cho vi dieu khien ESP32, ho tro doc du lieu chinh xac va on dinh cho cac thiet bi giao duc.
category=Sensors
url=
architectures=esp32
includes=BN_DHT11.h